### ISSUE TITLE
Voting or asking a question will sometimes show you signed in as someone else

### ISSUE THREAD

**Issue by Venefilyn** [IainMNorman/streamq#1]
So after logging in, creating a vote and upvoting a few questions, it will sometimes refresh and show a different user. This is a privacy issue as each email is shown publicly https://i.imgur.com/ih1X5jq.png

If you have voted with all your votes and asked all your questions, you can luckily no longer be logged in as someone else. Being logged in as someone else is only visual.

Geez Iain, what did you do! D:

**Comment by IainMNorman** [comment]
Ta Eric. There was overly vigorous output caching on the Home controller Index action for a while till I spotted it. Shouldn't still be doing it.

**Comment by IainMNorman** [comment]
Let me know if it is. Not seeing it here.

**Comment by IainMNorman** [comment]
It's hugely inefficient but knocked up very quickly :)

Would be best if voting was done via an API and I threw in a bit of a JS framework on the clientside. We'll see how it manages tonight! I'm gonna throw my remaining MSDN Azure credit at it for the hour.
